# Uncomment the next line to define a global platform for your project
platform :ios, '14.0'

target 'MyTestApp' do
  # Comment the next line if you don't want to use dynamic frameworks
 use_frameworks!

  # Pods for CocoaTest
  pod 'Evergage', :path => '../evergage-sdk-ios-1.3.2'
  
end
